# Generated by Django 5.0.3 on 2024-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
