# Generated by Django 5.0.3 on 2024-03-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
