# Generated by Django 5.0 on 2023-12-20 18:03

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.FileField(null=True, upload_to=posts.models.upload_to),
        ),
    ]
